POST http://localhost:8080/v1/users
Accept: application/json
Content-Type: application/json

{
  "sender": "user1"
}

###
POST http://localhost:8080/v1/stream-feed-credentials
Authorization: Bearer KA4hQjnPvypBkZ08CCX8cs/Vjug0nAAS5A+TzHwcp9E=
Accept: application/json
Content-Type: application/json

{}

###
